name: 'Secure Rsync Deploy'
description: 'Securely deploy code to a webserver via rsync over ssh'
author: 'Micah Wood'
branding:
  icon: 'upload-cloud'  
  color: 'red'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  DEPLOY_KEY:
    description: 'SSH private key'
    required: true
  FLAGS:
    description: 'Rsync flags'
    required: true
    default: '--archive --checksum --compress --delete-after --force --recursive --verbose'
  HOST:
    description: 'Remote host name or IP address (e.g. example.com or 101.186.66.124)'
    required: true
  LOCAL_PATH:
    description: 'Local folder to be synced, relative to the GitHub workspace.'
    required: true
    default: ''
  OPTIONS:
    description: 'Rsync options'
    required: true
    default: '--include-from=.distinclude --exclude-from=.distignore --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r'
  REMOTE_PATH:
    description: 'Remote path (e.g. /var/www/html/)'
    required: true
  USER: 
    description: 'Remote user name (e.g. root or deploy)'
    required: true